apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: {{ .Values.ingress.application.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: {{ .Values.application.service.name }}
              port:
                number: {{ .Values.ingress.application.port }}
  - host: {{ .Values.ingress.jaeger.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: jaeger-all-in-one
              port:
                number: {{ .Values.ingress.jaeger.port }}
  - host: {{ .Values.ingress.zipkin.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: zipkin-all-in-one
              port:
                number: {{ .Values.ingress.zipkin.port }}
  - host: {{ .Values.ingress.grafana.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
            service:
              name: grafana
              port:
                number: {{ .Values.ingress.grafana.port }}