apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      containers:
        - image: prom/prometheus:latest
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
          - mountPath: /etc/prometheus/
            name: prometheus-config-volume
      restartPolicy: Always
      volumes:
         - name: prometheus-config-volume
           configMap:
             name: prometheus
             items:
               - key: prometheus-config
                 path: prometheus.yml

---

apiVersion: v1
kind: Service
metadata:
  labels:
    component: prometheus
  name: prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    component: prometheus
  type: LoadBalancer #ClusterIP
status:
   loadBalancer: {}
