name: build_workflow

on:
  workflow_call:
  workflow_dispatch:
    inputs:  
    sonarUrl:
        required: false
        default: http://54.220.247.102:9000/
      sonarToken:
        required: false
        default:
      targetPath:
        required: false
        default: ./
        
env:
  targetPath: ${{ github.event.inputs.targetPath || './' }}
  sonarUrl: ${{ github.event.inputs.sonarUrl || 'http://54.220.247.102:9000/' }}
  sonarToken: ${{ github.event.inputs.sonarToken || secrets.SONARQUBE_TOKEN }}

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the application
        run: .github/workflows/scripts/build.sh

      - name: Archiving artifact
        run: pwd;ls -l;tar -cvf ./BuildOutput.tar -C ${{ env.targetPath }}/ .

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildOutput
          path: ./BuildOutput.tar
          
      - name: Download artifact from build job (current workflow)
        uses: actions/download-artifact@v2
        id: dowloadFromSamePipeline
        continue-on-error: true
        with:
          name: BuildOutput
          path: ${{ env.targetPath }}

      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v2
        id: downloadFromBuild
        continue-on-error: true
        if: ${{ steps.dowloadFromSamePipeline.outcome == 'failure' }}
        with:
          workflow: ${{ env.buildPipelineYamlName }}
          commit: ${{ github.sha }}
          check_artifacts:  true
          name: BuildOutput
          path: ${{ env.targetPath }}
          
      - name: Extracting archive
        run: tar -C ${{ env.targetPath }} -xf ${{ env.targetPath }}/BuildOutput.tar

      - name: SonarQube analysis
        run: .github/workflows/scripts/quality.sh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_URL: ${{ env.sonarUrl }}
          PROJECT_PATH: .    
