name: ci_workflow

on:
  #workflow_call:
  workflow_dispatch:
  
permissions:
  actions: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  node_build_workflow:
    uses: ./.github/workflows/build-pipeline.yml
